name: Deploy to GitHub Pages

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Build versioned release
        run: |
          npm run build -- --base=/BSix.com/${{ steps.version.outputs.VERSION }}/
          mkdir -p dist-final/${{ steps.version.outputs.VERSION }}
          cp -r dist/* dist-final/${{ steps.version.outputs.VERSION }}/
        
      - name: Build latest release
        run: |
          npm run build -- --base=/BSix.com/latest/
          mkdir -p dist-final/latest
          cp -r dist/* dist-final/latest/
          
      - name: Create index redirect
        run: |
          cat > dist-final/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>BSix.com - Redirecting...</title>
            <meta http-equiv="refresh" content="0; url=./latest/">
            <link rel="canonical" href="./latest/">
          </head>
          <body>
            <p>Redirecting to <a href="./latest/">latest version</a>...</p>
          </body>
          </html>
          EOF
          
      - name: Create versions manifest
        run: |
          cat > dist-final/versions.json << EOF
          {
            "latest": "${{ steps.version.outputs.VERSION }}",
            "versions": [
              "${{ steps.version.outputs.VERSION }}"
            ],
            "deployed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          }
          EOF
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-final'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## BSix.com Release ${{ steps.version.outputs.VERSION }}
            
            🚀 **Deployed to**: ${{ steps.deployment.outputs.page_url }}latest/
            📦 **Versioned URL**: ${{ steps.deployment.outputs.page_url }}${{ steps.version.outputs.VERSION }}/
            
            ### Changes
            See [CHANGELOG.md](./CHANGELOG.md) for detailed changes.
            
            ### Rollback
            If issues are found, rollback instructions are available in [ROLLBACK.md](./ROLLBACK.md).
          draft: false
          prerelease: false
